# home/fish-dispatch.nix — nixremote's fish integration: `<app>@<peer>`
# command dispatch (e.g. `firefox@some-peer`), matching the tmux@<host>/
# zellij@<host> convention already in use on this fleet. Purely additive on
# top of `nixremote.forward` — reads its peer list directly off `config`, no
# separate peer list to maintain here.
#
# ── DESIGN CHOICE: a conf.d/*.fish file, not `programs.fish.functions` ─────
# home-manager's own fish module (`programs.fish.enable` + `.functions`)
# takes over `~/.config/fish/config.fish` WHOLESALE — the same class of risk
# as `programs.ssh.enable` in forward.nix. A real machine can have a
# substantial vendor fish config already in play (e.g. `cachyos-fish-config`
# defines its OWN `fish_command_not_found`, inline in `config.fish`) that
# would be silently destroyed by handing the whole file to home-manager. So
# this module writes directly to `~/.config/fish/conf.d/nixremote-dispatch.fish`
# instead — fish's own standard, safe extension point: every `conf.d/*.fish`
# file is sourced on every shell startup, AFTER `config.fish`, entirely
# independent of whether `programs.fish.enable` is set at all.
#
# ── GOTCHA (found via live testing): fish_command_not_found doesn't compose ─
# Verified directly, twice: fish looks up a function LITERALLY named
# `fish_command_not_found` and calls it directly — a DIFFERENTLY-named
# function decorated with `--on-event fish_command_not_found` does NOT also
# fire alongside it, contrary to what a generic pub/sub event model would
# suggest. So this module's conf.d file REDEFINES `fish_command_not_found`
# outright. Also verified: a later definition of the same function name
# cleanly REPLACES an earlier one (no stacking, no double-firing) as long as
# it is eagerly sourced (a `conf.d/*.fish` file is; a lazily-autoloaded
# `functions/*.fish` file of the same name is NOT — it's never even
# consulted if the name is already defined by the time it would be looked
# up). This module's version explicitly falls through to
# `__fish_default_command_not_found_handler` for anything it doesn't
# recognize — the exact same fallback any stock/vendor handler already uses
# — so enabling this changes nothing for ordinary command-not-found typos.
{ lib, config, ... }:
let
  cfg = config.nixremote.forward;
  peers = lib.attrNames cfg;

  caseBranch = name: ''
        case '*@${name}'
            ${cfg.${name}.scriptName} (string replace -r -- '@${name}$' "" "$cmd") $argv[2..]
            return $status
  '';
in
{
  options.nixremote.fishDispatch.enable = lib.mkEnableOption ''
    the `<app>@<peer>` fish command dispatch (e.g. `firefox@some-peer`),
    matching the tmux@<host>/zellij@<host> convention. Covers every peer
    already declared under `nixremote.forward` automatically — no separate
    peer list to maintain. Writes
    `~/.config/fish/conf.d/nixremote-dispatch.fish` only; never touches the
    rest of your fish config (see this module's header for why not
    `programs.fish.functions`)
  '';

  config = lib.mkIf (config.nixremote.fishDispatch.enable && peers != [ ]) {
    home.file.".config/fish/conf.d/nixremote-dispatch.fish".text = ''
      # Generated by nixremote (nixremote.fishDispatch.enable) — do not hand-edit.
      function fish_command_not_found
          set -l cmd $argv[1]
          switch "$cmd"
      ${lib.concatStrings (map caseBranch peers)}
          end
          __fish_default_command_not_found_handler $argv
      end
    '';
  };
}
