# home/fish-dispatch.nix — nixremote's fish integration: `<app>@<peer>`
# command dispatch (e.g. `firefox@some-peer`), matching the tmux@<host>/
# zellij@<host> convention already in use here. Purely additive on
# top of `nixremote.forward` — reads its peer list directly off `config`, no
# separate peer list to maintain here.
#
# ── DESIGN CHOICE: a conf.d/*.fish file, not `programs.fish.functions` ─────
# home-manager's own fish module (`programs.fish.enable` + `.functions`)
# takes over `~/.config/fish/config.fish` WHOLESALE — the same class of risk
# as `programs.ssh.enable` in forward.nix. A real machine can have a
# substantial vendor or hand-written fish config already in play, and handing
# the whole file to home-manager would silently destroy it. So this module
# writes directly to `~/.config/fish/conf.d/nixremote-dispatch.fish` instead
# — fish's own standard extension point: every `conf.d/*.fish` file is
# sourced on every shell startup, entirely independent of whether
# `programs.fish.enable` is set at all.
#
# ── LIMIT OF THAT PLACEMENT: conf.d is sourced BEFORE config.fish ──────────
# Not after. (Verified on fish 4.8.1 with a throwaway XDG_CONFIG_HOME holding
# both a config.fish and a conf.d/*.fish, each echoing and each defining
# `fish_command_not_found`: conf.d printed first, and the handler that fired
# on an unknown command was the config.fish one.) So conf.d protects an
# existing config.fish from being clobbered — the risk this module is
# avoiding — but does NOT protect this handler from the reverse: any
# config.fish that defines its own `fish_command_not_found` is sourced later
# and replaces this one outright. Nothing inside conf.d can fix that
# ordering; a machine in that situation has to stop defining the function in
# its config.fish, or make that definition do this dispatch itself.
#
# ── HARD LIMIT: this hook can never report an exit status ─────────────────
# fish calls `fish_command_not_found` and then IGNORES whatever it returns:
# the command's status is 127 unconditionally, fish prints its own
# command-not-found error on top of whatever the handler already printed, and
# the handler's stdout is redirected onto stderr. Verified on fish 4.8.1
# against a handler whose entire body is `return 0`; fish's own man page
# describes the hook as a place to "print a message", not a place to run a
# command. So a dispatched app really does launch and its window really does
# appear, yet every invocation also emits a spurious error and reports
# failure — unusable in `&&` chains, in scripts, or from anything that
# inspects a status. This module is therefore the OPEN-ENDED, INTERACTIVE
# fallback for apps nobody declared; `nixremote.forward.<peer>.apps` is the
# mechanism for the apps that matter, generating real `<app>@<peer>` and
# `<app>.<peer>` executables that work from any shell and exit with the app's
# own status.
#
# ── GOTCHA: fish_command_not_found doesn't compose ────────────────────────
# fish looks up a function LITERALLY named `fish_command_not_found` and
# calls it directly — a DIFFERENTLY-named function decorated with
# `--on-event fish_command_not_found` does NOT also fire alongside it,
# contrary to what a generic pub/sub event model would suggest. So this
# module's conf.d file REDEFINES `fish_command_not_found` outright. A later
# definition of the same function name cleanly REPLACES an earlier one (no
# stacking, no double-firing) as long as it is eagerly sourced (a
# `conf.d/*.fish` file is; a lazily-autoloaded `functions/*.fish` file of the
# same name is NOT — it's never even consulted if the name is already
# defined by the time it would be looked up). This module's version falls
# through to `__fish_default_command_not_found_handler` for anything it
# doesn't recognize — the same fallback any stock/vendor handler already
# uses — so enabling this changes nothing for ordinary command-not-found
# typos.
{ lib, config, ... }:
let
  cfg = config.nixremote.forward;
  peers = lib.attrNames cfg;

  caseBranch = name: ''
        case '*@${name}'
            ${cfg.${name}.scriptName} (string replace -r -- '@${name}$' "" "$cmd") $argv[2..]
            return $status
  '';
in
{
  options.nixremote.fishDispatch.enable = lib.mkEnableOption ''
    the `<app>@<peer>` fish command dispatch (e.g. `firefox@some-peer`),
    matching the tmux@<host>/zellij@<host> convention. Covers every peer
    already declared under `nixremote.forward` automatically — no separate
    peer list to maintain. Writes
    `~/.config/fish/conf.d/nixremote-dispatch.fish` only; never touches the
    rest of your fish config (see this module's header for why not
    `programs.fish.functions`)
  '';

  config = lib.mkIf (config.nixremote.fishDispatch.enable && peers != [ ]) {
    home.file.".config/fish/conf.d/nixremote-dispatch.fish".text = ''
      # Generated by nixremote (nixremote.fishDispatch.enable) — do not hand-edit.
      function fish_command_not_found
          set -l cmd $argv[1]
          switch "$cmd"
      ${lib.concatStrings (map caseBranch peers)}
          end
          __fish_default_command_not_found_handler $argv
      end
    '';
  };
}
