# home/shpool.nix — persistent remote shells without a terminal multiplexer UI.
#
# shpool owns the remote PTY and shell while the local terminal remains an ordinary terminal.
# This module deliberately gives shpool no keybinding and no prompt prefix: closing the terminal
# detaches, reconnecting attaches, and `exit` keeps its normal meaning (end the shell). The daemon
# lives on default.target rather than graphical-session.target, so a compositor or forwarded Foot
# disappearing does not take the shell with it.
#
# The daemon and client halves are independent. `server.enable` runs the local daemon; each entry
# in `peers` publishes `shpool@<peer>`/`shpool.<peer>` for attaching in the current terminal and,
# by default, `foot@<peer>`/`foot.<peer>` for opening the same session in a fresh LOCAL Foot. The
# peer's SSH alias is intentionally only a string: nixremote.forward may own the address cascade,
# but this module merely consumes the resulting alias and does not duplicate that transport logic.
{ lib, pkgs, config, ... }:
let
  cfg = config.nixremote.shpool;

  peerModule = { name, config, ... }: {
    options = {
      _peerName = lib.mkOption {
        type = lib.types.strMatching "[A-Za-z0-9_-]+";
        default = name;
        readOnly = true;
        internal = true;
        description = "Validated copy of this peer's attrsOf key.";
      };

      sshHost = lib.mkOption {
        type = lib.types.strMatching "[A-Za-z0-9_.:@-]+";
        default = config._peerName;
        description = ''
          OpenSSH host or alias to connect to. This is normally the same alias generated by
          nixremote.forward, so its LAN/overlay address cascade and host-key policy are reused.
        '';
      };

      defaultSession = lib.mkOption {
        type = lib.types.strMatching "[A-Za-z0-9][A-Za-z0-9_.-]*";
        default = "main";
        description = "Session used when the generated command is invoked without an argument.";
      };

      remoteBinary = lib.mkOption {
        type = lib.types.strMatching "[A-Za-z0-9_./+-]+";
        default = "shpool";
        description = ''
          shpool binary as resolved by the remote SSH command. A bare name uses sshd's command
          PATH; use an absolute path only when the remote host does not publish it there.
        '';
      };
    };
  };

  configText = ''
    # Generated by nixremote. shpool must remain transparent to the terminal.
    keybinding = []
    nodaemonize = true
    prompt_prefix = ${builtins.toJSON cfg.server.promptPrefix}
    session_restore_mode = ${
      if cfg.server.restoreLines == null
      then builtins.toJSON cfg.server.restoreMode
      else "{ lines = ${toString cfg.server.restoreLines} }"
    }
  '';

  validRuntimeSession = ''
    case "$session" in
      ""|[!A-Za-z0-9]*|*[!A-Za-z0-9_.-]*)
        echo "nixremote shpool: session names must start with an alphanumeric character and contain only A-Z, a-z, 0-9, dot, underscore, or hyphen: $session" >&2
        exit 64
        ;;
    esac
  '';

  mkAttach = peer: commandName:
    let
      remotePrefix = lib.escapeShellArgs [ peer.remoteBinary "attach" "-f" ];
    in
    pkgs.writeShellScriptBin commandName ''
      if [ "$#" -gt 1 ]; then
        echo "usage: ${commandName} [SESSION]" >&2
        exit 64
      fi

      session="''${1:-${peer.defaultSession}}"
      ${validRuntimeSession}

      # One string reaches the remote shell. The dynamic session is safe to single-quote because
      # the validation above excludes quotes and every other shell metacharacter.
      remote_command=${lib.escapeShellArg remotePrefix}" '$session'"
      exec ${lib.escapeShellArg cfg.client.sshBinary} -t -- ${lib.escapeShellArg peer.sshHost} "$remote_command"
    '';

  mkTerminal = peer: attachPackage: commandName:
    pkgs.writeShellScriptBin commandName ''
      exec ${lib.escapeShellArg cfg.terminal.binary} \
        --app-id=${lib.escapeShellArg "foot@${peer._peerName}"} \
        --title=${lib.escapeShellArg peer._peerName} \
        -- ${attachPackage}/bin/shpool@${peer._peerName} "$@"
    '';

  packagesForPeer = _: peer:
    let
      attachAt = mkAttach peer "shpool@${peer._peerName}";
      attachDot = mkAttach peer "shpool.${peer._peerName}";
    in
    [ attachAt attachDot ]
    ++ lib.optionals cfg.terminal.enable [
      (mkTerminal peer attachAt "foot@${peer._peerName}")
      (mkTerminal peer attachAt "foot.${peer._peerName}")
    ];
in
{
  options.nixremote.shpool = {
    server = {
      enable = lib.mkEnableOption "the local persistent shpool daemon";

      binary = lib.mkOption {
        type = lib.types.str;
        default = "shpool";
        example = "/usr/bin/shpool";
        description = ''
          Binary used by the local systemd user service. Package installation belongs to
          nixremote's transport catalogue; this option only chooses the executable to run.
        '';
      };

      promptPrefix = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = ''
          Prefix injected into shells created by shpool. Empty by default so the prompt and the
          terminal behave exactly as they do outside shpool.
        '';
      };

      restoreMode = lib.mkOption {
        type = lib.types.enum [ "screen" "simple" ];
        default = "screen";
        description = ''
          Reattach behavior when restoreLines is null. "screen" redraws the last visible screen;
          "simple" only asks full-screen programs to redraw and discards detached output.
        '';
      };

      restoreLines = lib.mkOption {
        type = lib.types.nullOr lib.types.ints.positive;
        default = null;
        example = 1000;
        description = ''
          Restore this many lines on reattach, overriding restoreMode. Null keeps the opinionated
          screen-sized restore and avoids dumping a large backlog into a freshly opened terminal.
        '';
      };
    };

    client.sshBinary = lib.mkOption {
      type = lib.types.str;
      default = "ssh";
      example = "/usr/bin/ssh";
      description = "OpenSSH client used by every generated peer wrapper.";
    };

    terminal = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Publish foot@peer and foot.peer commands which open a local Foot around the persistent
          remote shell. Disable this on a non-Wayland or non-Foot client; shpool@peer remains.
        '';
      };

      binary = lib.mkOption {
        type = lib.types.str;
        default = "foot";
        example = "/usr/bin/foot";
        description = "Local Foot binary used by the generated terminal commands.";
      };
    };

    peers = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule peerModule);
      default = { };
      description = ''
        Remote hosts that publish persistent shell commands. Each command accepts zero or one
        session name; invoking it again reattaches with `shpool attach -f` so a stale SSH transport
        cannot leave the session inaccessible.
      '';
    };
  };

  config = lib.mkMerge [
    (lib.mkIf cfg.server.enable {
      xdg.configFile."shpool/config.toml".text = configText;

      systemd.user.sockets.shpool = {
        Unit = {
          Description = "Shpool shell session pooler";
          # A Home Manager switch must not bounce the socket underneath live sessions.
          X-SwitchMethod = "keep-old";
        };
        Socket = {
          ListenStream = "%t/shpool/shpool.socket";
          SocketMode = "0600";
        };
        Install.WantedBy = [ "sockets.target" ];
      };

      systemd.user.services.shpool = {
        Unit = {
          Description = "Shpool persistent shell session daemon";
          Requires = [ "shpool.socket" ];
          After = [ "shpool.socket" ];
          # sd-switch loads the replacement for the next start but leaves the process which owns
          # today's PTYs alone. An explicit restart remains deliberately session-destructive.
          X-SwitchMethod = "keep-old";
        };
        Service = {
          Type = "simple";
          ExecStart = lib.escapeShellArgs [ cfg.server.binary "daemon" ];
          KillMode = "mixed";
          TimeoutStopSec = "2s";
          SendSIGHUP = true;
        };
        Install.WantedBy = [ "default.target" ];
      };
    })

    {
      home.packages = lib.flatten (lib.mapAttrsToList packagesForPeer cfg.peers);
    }
  ];
}
